empty_set=set()
print("Empty Set:", empty_set)
empty_set.add("Simoni")
print("Set after adding an element:", empty_set)
empty_set.add("Ishaan")
print("Set after adding another element:", empty_set)
empty_set.add("Vedant")
print("Set after adding a third element:", empty_set)
empty_set.remove("Simoni")
print("Set after removing an element:", empty_set)
empty_set.discard("Ishaan")
print("Set after discarding an element:", empty_set)
empty_set.clear()
print("Set after clearing all elements:", empty_set)