Bio={"Name":"Simoni","Age":20,"Salary":1000,"Address":"Colombo","Phone":1234567890}
print("Bio:", Bio)
Bio.update({"Email":"sawantsimoni@gmail.com"})
print("Bio after update:", Bio)
Bio.pop("Phone")
print("Bio after removing Phone:", Bio)
Bio.keys()
print("Keys in Bio:", Bio.keys())
Bio.values()
print("Values in Bio:", Bio.values())
Bio.items()
print("Items in Bio:", Bio.items())
Bio.get("Name")
print("Name in Bio:", Bio.get("Name"))
Bio.clear()
print("Bio after clearing:", Bio)
