tuple=("ramen", "sushi", "tempura", "udon", "sashimi")
print("The tuple is:", tuple)
rem=input("Enter an item to remove from the tuple:")
print("The tuple after removing", rem, "is:", tuple)
add=input("Enter an item to add to the tuple:")
print("The tuple after adding", add, "is:", tuple)
sor=input("Enter 'asc' to sort in ascending order:") 
print("The tuple in ascending order is:", sorted(tuple))   
cou=input("Enter an item to count in the tuple:")
count=tuple.count(cou)
print("The count of", cou, "in the tuple is:", count)
ind=input("Enter an item to find its index in the tuple:")
index=tuple.index(cou)
print("The index of", ind, "in the tuple is:", index)
